### ISSUE TITLE
Save more state

### ISSUE THREAD

**Issue by akx** [akx/illuminatrix#12]
Via #11: 

> the panel doesn't remember my choices

@PatrikTheDev What choices aren't remembered that should be?

**Comment by PatrikTheDev** [comment]
1) brightness preference
<img width="557" alt="image" src="https://github.com/akx/illuminatrix/assets/25883885/3bed2074-f06a-4829-ac4b-b6de0bd855f6">

2) potentially save the search filters in the UI? It's much less of a problem than the brightness preference but it would be helpful if the page remembered my last selected search filter
<img width="473" alt="image" src="https://github.com/akx/illuminatrix/assets/25883885/934eeaac-0b77-466b-8015-cecf20560d04">

**Comment by akx** [comment]
Done via #13!
